docs: Add docs for running headscale on sealos
juanfont/headscale pull request #1666
Opened 2023-12-28 10:26 UTC by yangchuansheng

- [ ] read the [CONTRIBUTING guidelines](README.md#contributing)
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

2024-02-09 23:03 UTC, ohdearaugustin requested changes
Generally well written documentation. Just added some minor suggestions.

2024-02-09 23:03 UTC, ohdearaugustin commented on docs/running-headscale-sealos.md
> +Sealos is a cloud operating system distribution based on the Kubernetes kernel. It adopts a cloud-native approach, discarding traditional cloud computing architecture, and shifting towards a new arch
A bit much advertisement for my taste (:

2024-03-14 10:22 UTC, kradalby commented
I'm sceptical to having to specific documentation for niche distributions, but if it is community maintained, I suppose it might be fine.

What do you think @ohdearaugustin ?

2024-03-14 21:24 UTC, ohdearaugustin commented
I think the same. I already asked to changes some things, therefore with disclaimer I don't see any problem with it.

2024-03-19 21:46 UTC, ohdearaugustin commented
@yangchuansheng would you please fix the suggestion otherwise I will close the PR.

2024-04-10 08:11 UTC, yangchuansheng commented
> @yangchuansheng would you please fix the suggestion otherwise I will close the PR.

Ok, I'll fix the suggestion soon

2024-04-10 08:44 UTC, yangchuansheng commented
> @yangchuansheng would you please fix the suggestion otherwise I will close the PR.

done! Please kindly review the modifications and let me know if there's anything else that needs to be addressed or if you have any further suggestions.

2024-04-11 21:00 UTC, ohdearaugustin requested changes
Small changes, mainly wording

2024-04-11 21:00 UTC, ohdearaugustin commented on docs/running-headscale-sealos.md
> +1. Click the following prebuilt template:
Maybe add which version you are installing.

2024-04-14 16:08 UTC, yangchuansheng commented
> Small changes, mainly wording

Done.

2024-04-18 03:28 UTC, yangchuansheng commented
Please let me know if there's anything else I should work on or if you have any further feedback, thanks.

2024-04-21 13:22 UTC, ohdearaugustin approved these changes

2024-04-21 14:43 UTC, merged