Fix typos
juanfont/headscale pull request #1860
Opened 2024-04-08 06:05 UTC by majst01

Fix all typos found with https://github.com/crate-ci/typos, later we can add this to the CI to prevent further introduction typos.

- [x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

2024-04-11 20:46 UTC, ohdearaugustin approved these changes
Looks good and shouldn't change any code logic.

2024-04-11 21:06 UTC, ohdearaugustin commented
Please run prettier on docs/web-ui.md

2024-04-12 04:55 UTC, majst01 commented
> Please run prettier on docs/web-ui.md

done

2024-04-12 10:42 UTC, ohdearaugustin approved these changes

2024-04-21 13:20 UTC, ohdearaugustin commented
There have been a lot of changes can you please rebase the PR.

2024-04-21 13:37 UTC, majst01 commented
> There have been a lot of changes can you please rebase the PR.

Done

2024-04-21 16:36 UTC, ohdearaugustin commented
There are still some conflicts.

2024-04-21 18:57 UTC, ohdearaugustin requested changes
Delete your secrets from the kustomize

2024-04-21 18:57 UTC, ohdearaugustin commented on docs/examples/kustomize/base/secrets/private-key
I think you merge a local main and your secrets.

2024-04-21 18:57 UTC, ohdearaugustin commented on docs/examples/kustomize/base/site/public.env
I think you merge a local main and your env

2024-04-21 18:57 UTC, ohdearaugustin commented on docs/examples/kustomize/postgres/secrets/password
Another secret

2024-04-21 19:29 UTC, kradalby commented
I think we should just remove the whole kustomize stuff, I can open a pr for it tomorrow

2024-04-22 08:23 UTC, kradalby commented
@ohdearaugustin opened for removing kustomize #1906

2024-04-23 09:56 UTC, majst01 commented
Should be in a sane state finally :-)

2024-05-01 06:29 UTC, majst01 commented
synced with main again

2024-05-12 16:08 UTC, ohdearaugustin approved these changes

2024-05-19 21:49 UTC, ohdearaugustin commented
The unstable tailscale client is failing for the IntegrationTest (TestAuthKeyLogoutAndRelogin) this was not caused by this PR, but rather by an update of the client. @kradalby I hope it is okay to merge it.

2024-05-19 21:49 UTC, merged

2024-05-19 21:51 UTC, kradalby commented
Yes it's been in the works for a bit, great getting it in

2024-05-20 06:55 UTC, majst01 commented
Thanks