Linux installation documentation update
juanfont/headscale pull request #2054
Opened 2024-08-12 19:03 UTC by labeneator

- [x] have read the [CONTRIBUTING.md](./CONTRIBUTING.md) file
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [x] updated documentation if needed
- [ ] updated CHANGELOG.md

This small patch adds extra docs to the linux installation file.

1. Add one liners to figure out the architecture of a Debian/Ubuntu box and the latest available headscale package.
2. Adds a sample config.yml that will help people figure out a sane starting point -  took me a couple of hours to wrangle the listening ports and protocols to use.

2024-08-12 19:15 UTC, ohdearaugustin requested changes
I would rather link at the `Configure Headscale by editing the configuration file:` towards the example-config in the repository.

2024-08-12 19:15 UTC, ohdearaugustin commented on docs/running-headscale-linux.md
> +
We normally refer anyway to the [config-example.yaml](https://github.com/juanfont/headscale/blob/main/config-example.yaml). I don't want to maintain another example config.

2024-08-12 19:15 UTC, ohdearaugustin commented on docs/running-headscale-linux.md
> +    # HEADSCALE_VERSION="$(curl -v https://github.com/juanfont/headscale/releases/latest 2>&1 |grep location | awk -F'/' '{print $NF}' | sed -e 's/v//' | |tr -d '\r')"
```suggestion
    # HEADSCALE_VERSION="$(curl -v https://github.com/juanfont/headscale/releases/latest 2>&1 | grep location | awk -F'/' '{print $NF}' | sed -e 's/v//' | tr -d '\r')"
```
Fixed the shell call

2025-01-27 11:25 UTC, ohdearaugustin approved these changes
Looks good to me

2025-05-14 17:20 UTC, nblock commented
Sorry for not picking this up earlier. The structure of the docs changed. This section is now part of `docs/setup/install/official.md`. Please rebase against current main.

2025-06-19 17:36 UTC, nblock commented
No response, closing.

2025-06-19 17:36 UTC, closed without merging