Changed all the html into go using go-elem
juanfont/headscale pull request #2161
Opened 2024-09-30 16:16 UTC by amha-mersha

Created templates package in ./hscontrol/templates. Moved the registerWebAPITemplate into the templates package as a function to be called.

Replaced the apple and windows html files with go-elem.

- [X] have read the [CONTRIBUTING.md](./CONTRIBUTING.md) file
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

2024-09-30 16:28 UTC, kradalby approved these changes

2024-09-30 16:29 UTC, kradalby commented
@nblock if you have some time, can you do a quick skim of the content for windows and apple?

2024-09-30 16:30 UTC, kradalby commented
@amha-mersha can you delete the HTML templates so we are sure noone will update them in error?

2024-09-30 17:18 UTC, nblock commented
> @nblock if you have some time, can you do a quick skim of the content for windows and apple?

Sure, but I got this while building this commit:

```
error: hash mismatch in fixed-output derivation '/nix/store/xj7li14vnd7v6rnmlj5k7v2rqgm7hxw7-headscale-1e8fc3e-go-modules.drv':
         specified: sha256-+8dOxPG/Q+wuHgRwwWqdphHOuop0W9dVyClyQuh7aRc=
            got:    sha256-U5u4tRcCQ+aRIFzOOm0KWRX4BitWKwiHtq5m2DadNtA=
error: 1 dependencies of derivation '/nix/store/f2ds1pcql2haf3s2z3m68mfikcga7lix-headscale-1e8fc3e.drv' failed to build
```

2024-09-30 17:47 UTC, nblock requested changes
Some spaces are missing between element, probably due to minified output (left a few screenshots where spotted).

2024-09-30 17:47 UTC, nblock commented on hscontrol/templates/windows.go
> +			headerOne("headscale: Windows configuration"),
space missing:

![image](https://github.com/user-attachments/assets/8e6d8aad-d892-42eb-a696-6dddf023e3f8)

2024-09-30 17:47 UTC, nblock commented on hscontrol/templates/apple.go
> +					elem.Text("Install the official Tailscale iOS client from the"),
The space between `from the` and the appstore link is missing:

![image](https://github.com/user-attachments/assets/512f0bb3-b94d-42b3-bdac-2a1210dc6ef0)

2024-09-30 17:47 UTC, nblock commented on hscontrol/templates/apple.go
> +					elem.I(nil, elem.Text("not")),
When rendered, there is no space between those elements:


![image](https://github.com/user-attachments/assets/8f2c9a4c-65ad-47d1-9d69-b3ab0dd9a804)

2024-09-30 17:47 UTC, nblock commented on hscontrol/templates/apple.go
> +					elem.I(nil, elem.Text("(non-SSO)")),
missing space: 

![image](https://github.com/user-attachments/assets/831a3abb-54c9-40e7-83d5-1f1a7aa64d1c)

2024-09-30 17:47 UTC, nblock commented on hscontrol/templates/apple.go
> +					elem.Text(fmt.Sprintf(`Enter "%s" under "Alternate Coordination Server URL`,url)),
The closing `"` is missing after `Coordination Server URL`

2024-09-30 18:43 UTC, amha-mersha commented
@nblock I think it is now fixed

2024-10-01 04:18 UTC, nblock commented
> @nblock I think it is now fixed

That was quick, thx! 

Found one additional location where the space is lost: 

![image](https://github.com/user-attachments/assets/0531a508-4d62-453c-9c7b-67564d428092)

2024-10-02 13:52 UTC, amha-mersha commented
how about now @nblock . sorry to take your time for this things

2024-10-02 14:06 UTC, nblock approved these changes

2024-10-02 15:56 UTC, kradalby commented
Linter and `TestAuthKeyLogoutAndRelogin` is expected, but can you have a look at updating the build flake sha?

2024-10-03 10:02 UTC, kradalby commented
A rebase should also fix the failing integration tests.

2024-10-03 10:05 UTC, amha-mersha commented
So should I first rebase and commit

2024-10-03 10:56 UTC, kradalby commented
yep that sounds best

2024-10-03 11:31 UTC, amha-mersha commented
I have rebased and pushed again

2024-10-03 11:42 UTC, kradalby commented
Think the nix flake needs to be update again, haha, we are very close!

2024-10-03 11:43 UTC, amha-mersha commented
do I update that and how

2024-10-03 12:03 UTC, kradalby commented
In the failing build there is a new hash that needs to replace the old one one flake.nix, so a search replace should be good.
 Sent from Proton Mail for iOS 
On Thu, Oct 3, 2024 at 13:44, Amha Mersha ***@***.***&gt; wrote:   do I update that and how —
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because your review was requested.Message ID: ***@***.***&gt;

2024-10-04 10:40 UTC, kradalby commented
I fixed it up and will merge it when the test runs :) Thanks @amha-mersha, if you feel like more challenges there is one linked in the issue for OIDC page that is trickier because it has more CSS.

2024-10-04 11:09 UTC, amha-mersha commented
Thank you @kradalby for taking the time and guiding me. And for the other one, sure I look into it and get back to you

2024-10-04 11:39 UTC, merged

2024-10-04 11:47 UTC, amha-mersha commented
Could you share me the issue, I couldn't find it.

2024-10-04 12:39 UTC, kradalby commented
https://github.com/juanfont/headscale/issues/2115 @amha-mersha