Feature tvos documentation
juanfont/headscale pull request #2226
Opened 2024-11-04 22:49 UTC by shokinn

- [x] have read the [CONTRIBUTING.md](./CONTRIBUTING.md) file
- [ ] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [x] updated documentation if needed
- [ ] updated CHANGELOG.md

## Summary

- Documentation
  - Updated `docs/about/clients.md`, added `tvOS` as client.
  - Updated `docs/usage/connect/apple.md`, added Installation and configuration documentation for tvOS.
  - Updated `hscontrol/templates/apple.go` to also display the tvOS configuration at `/apple` on a deployed headscale instance.

2024-11-05 16:08 UTC, nblock requested changes
Thanks for your contribution!

I left a few minor suggestions for the docs part.

2024-11-05 16:08 UTC, nblock commented on hscontrol/templates/apple.go
> +						"Go Settings (the apple tvOS settings) > Apps > Tailscale",
Open Settings …

2024-11-05 18:24 UTC, shokinn commented
Sounds fair.
I've added the requested changes.

2024-11-06 05:46 UTC, nblock approved these changes

2024-11-06 15:02 UTC, kradalby commented on hscontrol/templates/apple.go
> +					elem.Text("Select \"Install VPN configuration\""),
```suggestion
					elem.Text(`Select "Install VPN configuration"`),
```

for the places its escaped, makes it a bit easier to read.

2024-11-07 14:56 UTC, merged