added cli options to output ACLs
juanfont/headscale pull request #581
Opened 2022-05-12 11:08 UTC by samson4649

- [x] read the [CONTRIBUTING guidelines](README.md#user-content-contributing)
- [x] raised a GitHub issue or discussed it on the projects chat beforehand
- [ ] added unit tests
- [ ] added integration tests
- [ ] updated documentation if needed
- [ ] updated CHANGELOG.md

Drafted to Fix #492

2022-05-12 11:18 UTC, samson4649 commented
Requires integration testing with separate instances of headscale per test or by dynamically loading ACLs into a single running instance (issue #582 )

2022-05-14 11:33 UTC, restanrm requested changes

2022-05-14 11:33 UTC, restanrm commented on cmd/headscale/cli/acls.go
> +		policy := h.GetACLPolicy()
This won't do, you need to go through the protobuf API for this. Add message type and response in proto folder, generate code via `make generate` then edit `grpcv1.go` to add server-side part

2022-06-17 08:13 UTC, samson4649 commented
@restanrm - as discussed, changes have been made to implement this over the grpc server.

2022-06-17 14:35 UTC, restanrm commented
It behaves as expected what do you think of this @kradalby ?

2022-06-20 04:48 UTC, samson4649 commented
This still needs some things fixed up - still working on it

2022-06-20 07:13 UTC, samson4649 commented
g2g now - ready for review

2022-07-10 09:58 UTC, kradalby commented
Hi, I am happy to give this a go, apologise for the delay, can you do a pass through the linters (proto, golangci and prettier) and then we can merge?

And update the hash in `flake.nix` (see the fail build)

2022-07-25 22:45 UTC, juanfont commented
Hey @samson4649, apologies for the delay. Can you check the conflicts?

2022-08-09 19:46 UTC, juanfont commented
@samson4649 can you check the (minor) conflicts? I think we are pretty ready to merge.

2022-08-12 10:27 UTC, juanfont commented
@samson4649 we have the linters working again, and found a couple of minor things here.

There is also an issue with a dependency. Can you have a look? Thanks!!

2022-08-13 09:09 UTC, juanfont reviewed
In addition to those comments, if you make changes to go.mod and go.sum, you need to update its checksum in `flake.nix`.

2022-08-13 09:09 UTC, juanfont commented on go.mod
> -	google.golang.org/genproto v0.0.0-20220808204814-fd01256a5276
Do not downgrade, please

2022-08-13 09:09 UTC, juanfont commented on go.mod
> -	inet.af/netaddr v0.0.0-20220617031823-097006376321
Downgrade :(

2022-08-13 09:09 UTC, juanfont commented on go.mod
> -	github.com/hashicorp/go-version v1.4.0 // indirect
Same

2022-08-13 09:09 UTC, juanfont commented on acls.go
> +func ACLProtoToStruct(v *v1.ACLPolicy) (*ACLPolicy, error) {
Here the linter is complaining

> parameter name 'v' is too short for the scope of its usage (varnamelen)


Replace `v`for `policy` or something like this, for instance.

2022-08-13 09:09 UTC, juanfont commented on acls.go
> +	}
```suggestion
	}
	
```

2022-08-13 09:09 UTC, juanfont commented on acls.go
> +}
```suggestion
}

```

2022-08-13 09:09 UTC, juanfont commented on cmd/headscale/cli/acls.go
> +		return
```suggestion
```

2022-08-13 09:09 UTC, juanfont commented on cmd/headscale/cli/acls.go
> +		return
not required

2023-05-10 10:32 UTC, closed without merging